#include "egl_context.h"
EglContext::~EglContext(){release();}
bool EglContext::initialize(){std::lock_guard<std::mutex>l(mutex_);if(initialized_)return true;display_=eglGetDisplay(EGL_DEFAULT_DISPLAY);if(display_==EGL_NO_DISPLAY||eglInitialize(display_,nullptr,nullptr)!=EGL_TRUE)return false;if(!loadExtensions()){eglTerminate(display_);display_=EGL_NO_DISPLAY;return false;}initialized_=true;return true;}
bool EglContext::createOffscreenContext(){if(!initialize())return false;const EGLint a[]={EGL_RENDERABLE_TYPE,EGL_OPENGL_ES3_BIT,EGL_SURFACE_TYPE,EGL_PBUFFER_BIT|EGL_WINDOW_BIT,EGL_RED_SIZE,8,EGL_GREEN_SIZE,8,EGL_BLUE_SIZE,8,EGL_ALPHA_SIZE,8,EGL_NONE};EGLint n=0;if(!eglChooseConfig(display_,a,&config_,1,&n)||!n)return false;const EGLint ca[]={EGL_CONTEXT_CLIENT_VERSION,3,EGL_NONE};context_=eglCreateContext(display_,config_,EGL_NO_CONTEXT,ca);if(context_==EGL_NO_CONTEXT)return false;const EGLint pa[]={EGL_WIDTH,1,EGL_HEIGHT,1,EGL_NONE};surface_=eglCreatePbufferSurface(display_,config_,pa);if(surface_==EGL_NO_SURFACE)return false;return eglMakeCurrent(display_,surface_,surface_,context_)==EGL_TRUE;}
EGLSurface EglContext::createWindowSurface(ANativeWindow*w){if(!w)return EGL_NO_SURFACE;const EGLint a[]={EGL_NONE};return eglCreateWindowSurface(display_,config_,w,a);}
void EglContext::release(){std::lock_guard<std::mutex>l(mutex_);if(display_!=EGL_NO_DISPLAY){eglMakeCurrent(display_,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);if(context_!=EGL_NO_CONTEXT)eglDestroyContext(display_,context_);if(surface_!=EGL_NO_SURFACE)eglDestroySurface(display_,surface_);eglTerminate(display_);}display_=EGL_NO_DISPLAY;context_=EGL_NO_CONTEXT;surface_=EGL_NO_SURFACE;config_=nullptr;initialized_=false;}
EGLImageKHR EglContext::createEglImageFromBuffer(AHardwareBuffer*b){if(!b||!eglCreateImageKHR_||display_==EGL_NO_DISPLAY)return EGL_NO_IMAGE_KHR;auto c=eglGetNativeClientBufferANDROID_(b);if(!c)return EGL_NO_IMAGE_KHR;const EGLint a[]={EGL_IMAGE_PRESERVED_KHR,EGL_TRUE,EGL_NONE};return eglCreateImageKHR_(display_,EGL_NO_CONTEXT,EGL_NATIVE_BUFFER_ANDROID,c,a);}
void EglContext::destroyEglImage(EGLImageKHR i){if(i!=EGL_NO_IMAGE_KHR&&eglDestroyImageKHR_)eglDestroyImageKHR_(display_,i);}
bool EglContext::loadExtensions(){eglCreateImageKHR_=reinterpret_cast<PFNEGLCREATEIMAGEKHRPROC>(eglGetProcAddress("eglCreateImageKHR"));eglDestroyImageKHR_=reinterpret_cast<PFNEGLDESTROYIMAGEKHRPROC>(eglGetProcAddress("eglDestroyImageKHR"));eglGetNativeClientBufferANDROID_=reinterpret_cast<PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC>(eglGetProcAddress("eglGetNativeClientBufferANDROID"));return eglCreateImageKHR_&&eglDestroyImageKHR_&&eglGetNativeClientBufferANDROID_;}
